spring.application.name=testy-multi-module
server.port=${SERVER_PORT:8080}
server.servlet.session.timeout=${SERVER_SESSION_TIMEOUT:30m}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/testy_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:200612yhx}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
testy.security.root.username=${TESTY_ROOT_USERNAME:rootadmin}
testy.security.root.email=${TESTY_ROOT_EMAIL:root@testy.local}
testy.security.root.password=${TESTY_ROOT_PASSWORD:Root@123456}
